# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: chat CI

on:
  push:
    branches: ['master']

env:
  SERVER_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
  cache-name: chat

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 上传打包资源
      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }} # 服务器私钥
          ARGS: '-avz --delete'
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
          REMOTE_USER: ${{ secrets.USER_NAME }} # 服务器用户名
          TARGET: ${{ secrets.TARGET }} #  服务器目标路径
          EXCLUDE: '.env, /node_modules/ /public/'

      # 连接服务器执行脚本
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器IP地址
          username: ${{ secrets.USER_NAME }} # 服务器用户名
          key: ${{ secrets.ACCESS_TOKEN }} # 服务器私钥
          script: |
            cd ${{ secrets.TARGET }}
            pnpm install
            pnpm build
            pm2 restart chat_backstage
